# Generated by Django 5.1.6 on 2025-03-12 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=3)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='venue_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
