# Generated by Django 5.2 on 2025-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
