# Generated by Django 5.2 on 2025-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='Anonym', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
