# Generated by Django 5.2 on 2025-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_booking_user_name_booking_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='end',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='venue',
            name='start',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='venue',
            name='working_days',
            field=models.CharField(default='1:2:3:4:5:6:7', help_text="Store days as colon-separated numbers like '1:2:5'", max_length=20),
        ),
    ]
